import { z } from 'zod';

export const translationSchema = z.object({
  detectedSourceLanguage: z.string().describe('The language of the source text'),
  translatedText: z.string().describe('The translated text'),
  aiGenerated: z.literal(true).describe('Whether the translation was generated by AI'),
});
