import { z } from 'zod';

export const translationSchema = z.object({
  detectedSourceLanguage: z
    .string()
    .describe(
      'ISO 639-1 code of the language the source text is written in, e.g. "de", "en", "it"'
    ),
  translatedText: z.string().describe('The translated text'),
  aiGenerated: z.literal(true).describe('Whether the translation was generated by AI'),
});

export const retranslateSchema = z.object({
  translatedText: z.string().describe('The re-translated text, considering the comment'),
  aiGenerated: z.literal(true).describe('Whether the re-translation was generated by AI'),
});
