#!/usr/bin/env bash
# =============================================================================
# KI Translator KMU — Demo Setup
# =============================================================================
# Brings a fresh clone to a running demo with no accounts and no API keys:
# local Supabase (auth + database) and a containerised Ollama, wired together
# by a generated env file. Invoked by `pnpm demo`, which runs the dev server
# afterwards.
#
# Only prerequisite: Docker is running.
# =============================================================================
set -euo pipefail

cd "$(dirname "$0")/.."

# Next.js ranks .env.development.local above .env.local, so the demo can point the
# app at the local stack without overwriting a contributor's own .env.local (which
# normally points at the hosted Supabase project). `pnpm demo:down` removes it.
DEMO_ENV_FILE=".env.development.local"
MODEL="qwen2.5:7b"
OLLAMA_CONTAINER="ki-translator-kmu-ollama"

step() { printf '\n\033[1;34m▶ %s\033[0m\n' "$1"; }

if ! docker info > /dev/null 2>&1; then
  echo "Docker läuft nicht. Bitte Docker Desktop starten und erneut versuchen." >&2
  exit 1
fi

step "Supabase lokal starten (Datenbank + Auth)"
# Idempotent — exits 0 when the stack is already up. On first start it applies
# everything in supabase/migrations, so the translations table and its RLS
# policies exist without any manual step.
pnpm exec supabase start

step "Env-Datei schreiben: $DEMO_ENV_FILE"
{
  echo "# Generated by scripts/demo-setup.sh — not committed, safe to delete."
  pnpm exec supabase status -o env \
    --override-name api.url=NEXT_PUBLIC_SUPABASE_URL \
    --override-name auth.publishable_key=NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY \
    | grep -E '^NEXT_PUBLIC_SUPABASE_(URL|PUBLISHABLE_KEY)='
  # The demo runs on the local model so it costs nothing and needs no API key.
  echo "AI_PROVIDER=ollama"
} > "$DEMO_ENV_FILE"

step "KI-Modell bereitstellen: $MODEL"
# A native Ollama already holds port 11434, which the container publishes on. Using
# it is not just conflict avoidance: the container keeps models in its own volume,
# so starting it anyway would store a second 4.7 GB copy of a model that is already
# on disk.
if curl -sf http://localhost:11434/api/tags > /dev/null 2>&1; then
  echo "Natives Ollama erkannt — Container wird nicht gestartet."
  if command -v ollama > /dev/null 2>&1; then
    ollama pull "$MODEL"
  else
    echo "Lade $MODEL über die Ollama-API (ca. 4,7 GB, kann dauern)…"
    curl -sS -X POST http://localhost:11434/api/pull \
      -d "{\"model\":\"$MODEL\"}" -o /dev/null
  fi
else
  docker compose --profile ollama up -d ollama
  printf 'Warte auf %s — der erste Lauf lädt ca. 4,7 GB ' "$MODEL"
  until docker exec "$OLLAMA_CONTAINER" ollama list 2> /dev/null | grep -qF "$MODEL"; do
    printf '.'
    sleep 5
  done
  printf ' fertig.\n'
fi

cat <<'EOF'

────────────────────────────────────────────────────────────
  Demo bereit.

  App        http://localhost:3000
  Anmeldung  "Als Gast anmelden" — keine Registrierung nötig
  Datenbank  http://127.0.0.1:54323 (Supabase Studio)

  Beenden:   pnpm demo:down
────────────────────────────────────────────────────────────
EOF
