// =============================================================================
// KI Translator KMU — Demo Setup
// =============================================================================
// Brings a fresh clone to a running demo with no accounts and no API keys:
// local Supabase (auth + database) and Ollama, wired together by a generated env
// file. Invoked by `pnpm demo`, which runs the dev server afterwards.
//
// Only prerequisite: Docker is running. Written in Node rather than shell so it
// works on Windows too — pnpm runs scripts through cmd.exe there, where bash is
// not on PATH by default, while Node is guaranteed to exist.
// =============================================================================
import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { setTimeout as sleep } from 'node:timers/promises';

const MODEL = 'qwen2.5:7b';
const OLLAMA_URL = 'http://localhost:11434';
// Next.js ranks .env.development.local above .env.local, so the demo can point the
// app at the local stack without overwriting a contributor's own .env.local (which
// normally points at the hosted Supabase project). `pnpm demo:down` removes it.
const DEMO_ENV_FILE = '.env.development.local';

const isWindows = process.platform === 'win32';
const supabaseBin = join('node_modules', '.bin', isWindows ? 'supabase.cmd' : 'supabase');

const step = (message) => console.log(`\n\x1b[1;34m▶ ${message}\x1b[0m`);

const run = (command, args, { capture = false } = {}) => {
  // Node refuses to spawn .cmd shims directly on Windows (CVE-2024-27980), so
  // those go through a shell — quoted, because the repo path may contain spaces.
  const viaShell = isWindows && command.endsWith('.cmd');
  const result = spawnSync(viaShell ? `"${command}"` : command, args, {
    stdio: capture ? ['inherit', 'pipe', 'inherit'] : 'inherit',
    shell: viaShell,
    encoding: 'utf8',
  });

  if (result.status !== 0) {
    throw new Error(`\`${command} ${args.join(' ')}\` schlug fehl (Exit ${result.status}).`);
  }
  return result.stdout ?? '';
};

const modelIsPresent = async () => {
  try {
    const response = await fetch(`${OLLAMA_URL}/api/tags`);
    if (!response.ok) return false;
    const { models = [] } = await response.json();
    return models.some((model) => model.name === MODEL);
  } catch {
    return false;
  }
};

const ollamaIsReachable = async () => {
  try {
    return (await fetch(`${OLLAMA_URL}/api/tags`)).ok;
  } catch {
    return false;
  }
};

const commandExists = (command) =>
  spawnSync(command, ['--version'], { stdio: 'ignore', shell: isWindows }).status === 0;

const main = async () => {
  if (spawnSync('docker', ['info'], { stdio: 'ignore' }).status !== 0) {
    console.error('Docker läuft nicht. Bitte Docker Desktop starten und erneut versuchen.');
    process.exit(1);
  }

  step('Supabase lokal starten (Datenbank + Auth)');
  // Idempotent — exits 0 when the stack is already up. On first start it applies
  // everything in supabase/migrations, so the translations table and its RLS
  // policies exist without any manual step.
  run(supabaseBin, ['start']);

  step(`Env-Datei schreiben: ${DEMO_ENV_FILE}`);
  const status = run(
    supabaseBin,
    [
      'status',
      '-o',
      'env',
      '--override-name',
      'api.url=NEXT_PUBLIC_SUPABASE_URL',
      '--override-name',
      'auth.publishable_key=NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY',
    ],
    { capture: true }
  );

  const credentials = status
    .split('\n')
    .filter((line) => /^NEXT_PUBLIC_SUPABASE_(URL|PUBLISHABLE_KEY)=/.test(line));

  if (credentials.length !== 2) {
    throw new Error('Supabase lieferte keine URL/Key — läuft der lokale Stack?');
  }

  writeFileSync(
    DEMO_ENV_FILE,
    [
      '# Generated by scripts/demo-setup.mjs — not committed, safe to delete.',
      ...credentials,
      // The demo runs on the local model so it costs nothing and needs no API key.
      'AI_PROVIDER=ollama',
      '',
    ].join('\n')
  );

  step(`KI-Modell bereitstellen: ${MODEL}`);
  if (await ollamaIsReachable()) {
    // A native Ollama already holds port 11434, which the container publishes on.
    // Using it is not just conflict avoidance: the container keeps models in its
    // own volume, so starting it anyway would store a second 4.7 GB copy of a
    // model that is already on disk.
    console.log('Ollama läuft bereits — Container wird nicht gestartet.');

    if (await modelIsPresent()) {
      console.log(`${MODEL} ist vorhanden.`);
    } else if (commandExists('ollama')) {
      run('ollama', ['pull', MODEL]);
    } else {
      console.log(`Lade ${MODEL} über die Ollama-API (ca. 4,7 GB, kann dauern)…`);
      await fetch(`${OLLAMA_URL}/api/pull`, {
        method: 'POST',
        body: JSON.stringify({ model: MODEL }),
      });
    }
  } else {
    run('docker', ['compose', '--profile', 'ollama', 'up', '-d', 'ollama']);
    process.stdout.write(`Warte auf ${MODEL} — der erste Lauf lädt ca. 4,7 GB `);
    while (!(await modelIsPresent())) {
      process.stdout.write('.');
      await sleep(5000);
    }
    process.stdout.write(' fertig.\n');
  }

  console.log(`
────────────────────────────────────────────────────────────
  Demo bereit.

  App        http://localhost:3000
  Anmeldung  "Als Gast anmelden" — keine Registrierung nötig
  Datenbank  http://127.0.0.1:54323 (Supabase Studio)

  Beenden:   pnpm demo:down
────────────────────────────────────────────────────────────`);
};

main().catch((error) => {
  console.error(`\n${error.message}`);
  process.exit(1);
});
