// =============================================================================
// KI Translator KMU — Demo Setup
// =============================================================================
// Brings a fresh clone to a running demo with no accounts and no API keys: local
// Supabase (auth + database) and Ollama, wired together by a generated env file.
// Invoked by `pnpm demo`, which starts the dev server afterwards.
//
// Only prerequisite: Docker is running.
//
// Node, not shell: pnpm runs scripts through cmd.exe on Windows, where bash is not
// on PATH after a default Git install.
// =============================================================================
import { writeFileSync } from 'node:fs';

import { ensureOllamaModel, MODEL } from './ollama.mjs';
import { fail, requireDocker, run, step, supabaseBin } from './shared.mjs';

// Next.js ranks .env.development.local above .env.local, so the demo can point the
// app at the local stack without overwriting a contributor's own .env.local, which
// normally points at the hosted Supabase project. `pnpm demo:down` removes it.
const DEMO_ENV_FILE = '.env.development.local';

const writeEnvFile = () => {
  const status = run(
    supabaseBin,
    [
      'status',
      '-o',
      'env',
      '--override-name',
      'api.url=NEXT_PUBLIC_SUPABASE_URL',
      '--override-name',
      'auth.publishable_key=NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY',
    ],
    { capture: true }
  );

  const credentials = status
    .split('\n')
    .filter((line) => /^NEXT_PUBLIC_SUPABASE_(URL|PUBLISHABLE_KEY)=/.test(line));

  if (credentials.length !== 2) {
    throw new Error('Supabase lieferte keine URL und keinen Key — läuft der lokale Stack?');
  }

  writeFileSync(
    DEMO_ENV_FILE,
    [
      '# Generated by scripts/demo-setup.mjs — not committed, safe to delete.',
      ...credentials,
      // The demo runs on the local model, so it costs nothing and needs no API key.
      'AI_PROVIDER=ollama',
      '',
    ].join('\n')
  );
};

const main = async () => {
  requireDocker();

  step('Supabase lokal starten (Datenbank + Auth)');
  // Idempotent — exits 0 when the stack is already up. On first start it applies
  // everything in supabase/migrations, so the translations table and its RLS
  // policies exist without any manual step.
  run(supabaseBin, ['start']);

  step(`Env-Datei schreiben: ${DEMO_ENV_FILE}`);
  writeEnvFile();

  step(`KI-Modell bereitstellen: ${MODEL}`);
  await ensureOllamaModel();

  console.log(`
────────────────────────────────────────────────────────────
  Demo bereit.

  App        http://localhost:3000
  Anmeldung  "Als Gast anmelden" — keine Registrierung nötig
  Datenbank  http://127.0.0.1:54323 (Supabase Studio)

  Beenden:   pnpm demo:down
────────────────────────────────────────────────────────────`);
};

main().catch(fail);
